<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-C1IFLQ8" failures="0" tests="5" name="testcases.com.bankguru.customer.Customer_03_Delete_Customer" time="13.382" errors="1" timestamp="10 Oct 2023 15:08:41 GMT" skipped="4">
  <testcase classname="testcases.com.bankguru.customer.Customer_03_Delete_Customer" name="beforeClass" time="13.382">
    <error message="Keys to send should be a not null CharSequence" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:97)
at commons.BasePage.sendkeyToElement(BasePage.java:179)
at pageObjects.LoginPageObject.inputToUserIDTextbox(LoginPageObject.java:23)
at testcases.com.bankguru.customer.Customer_03_Delete_Customer.beforeClass(Customer_03_Delete_Customer.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- beforeClass -->
  <testcase classname="testcases.com.bankguru.customer.Customer_03_Delete_Customer" name="TC_05_Delete_Customer_Successful" time="0.000">
    <skipped/>
  </testcase> <!-- TC_05_Delete_Customer_Successful -->
  <testcase classname="testcases.com.bankguru.customer.Customer_03_Delete_Customer" name="TC_02_Delete_Customer_With_CustomerID_Have_Character" time="0.000">
    <skipped/>
  </testcase> <!-- TC_02_Delete_Customer_With_CustomerID_Have_Character -->
  <testcase classname="testcases.com.bankguru.customer.Customer_03_Delete_Customer" name="TC_01_Delete_Customer_With_CustomerID_Is_Empty" time="0.000">
    <skipped/>
  </testcase> <!-- TC_01_Delete_Customer_With_CustomerID_Is_Empty -->
  <testcase classname="testcases.com.bankguru.customer.Customer_03_Delete_Customer" name="TC_03_Delete_Customer_With_CustomerID_Have_Special_Character" time="0.000">
    <skipped/>
  </testcase> <!-- TC_03_Delete_Customer_With_CustomerID_Have_Special_Character -->
</testsuite> <!-- testcases.com.bankguru.customer.Customer_03_Delete_Customer -->
